INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111111A', 'ANA', 'FUENTES', '22/11/1977', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111112B', 'LUIS', 'PEREZ', '01/01/1959', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111113C', 'LETICIA', 'PASO', '23/12/1964', 1);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111114E', 'FRANCISCO', 'DOMINGUEZ', '04/10/1969', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111115F', 'JUAN', 'PRESA', '20/06/1977', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111116G', 'LUIS', 'MONTES', '16/09/1965', 1);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111117H', 'JOSE', 'MIGUEL', '12/05/1945', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111118J', 'JOSE', 'CASTELLANOS', '08/07/1942', 1);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111119K', 'MAITE', 'AGUILERA', '05/02/1985', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111120A', 'PEDRO', 'BARCELLOS', '04/09/1962', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111121B', 'JEAN PAUL', 'ROSAS', '25/12/1999', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111122C', 'NOEL', 'LEGRAND', '07/12/1963', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111123D', 'MARTA', 'GARCIA', '26/08/1952', 1);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111124E', 'IGOR', 'RODRIGUEZ', '13/04/1982', 1);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111125F', 'ALICIA', 'BLANCO', '27/11/1962', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111126G', 'DAVID', 'ROCA', '28/03/1980', 1);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111127H', 'LOREA', 'RIOS', '19/04/1985', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111128J', 'MANUEL', 'GARCIA', '18/01/1972', 0);
INSERT INTO Cliente (idCliente, dni, nombre, apellidos, fechaNacimiento, baja) VALUES (null, '11111129K', 'MARIA ', 'ZABALA', '24/01/1989', 0);



INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000001A', 'MARIA ', 'PEREZ', '28/03/1983', '01/03/2005', 'ESPAÑA', 'ACROBATA', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000002B', 'JOSE', 'DOMINGUEZ', '12/05/1976', '01/06/2007', 'ESPAÑA', 'RESPONSABLE', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000003C', 'FRANCISCO', 'ROSAS', '04/10/1977', '01/09/2008', 'ESPAÑA', 'MAGO', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000004D', 'DAVID', 'GARCIA', '23/12/1984', '01/12/2008', 'ESPAÑA', 'JEFE AREA', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000005E', 'NOEL', 'RODRIGUEZ', '18/01/1982', '02/01/2009', 'ESPAÑA', 'ACROBATA', 1);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000007F', 'LETICIA', 'BLANCO', '04/09/1972', '02/01/2009', 'ESPAÑA', 'RESPONSABLE', 1);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000008G', 'JUAN', 'CASTELLANOS', '05/02/1980', '01/07/2010', 'ESPAÑA', 'JEFE AREA', 1);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000009H', 'JOSE', 'AGUILERA', '08/07/1992', '01/07/2010', 'ESPAÑA', 'RESPONSABLE', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000010A', 'MANUEL', 'BARCELLOS', '27/11/1975', '01/08/2010', 'ESPAÑA', 'TAQUILLERO', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000011B', 'PEDRO', 'FUENTES', '15/08/1986', '01/02/2011', 'ESPAÑA', 'JEFE AREA', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000012C', 'ANA', 'PRESA', '01/01/1960', '01/06/2011', 'ESPAÑA', 'RESPONSABLE', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000013D', 'MAITE', 'BRAIDA', '13/04/2000', '01/06/2011', 'ESPAÑA', 'ACROBATA', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000014E', 'IGOR', 'CIRIO', '20/06/1987', '01/03/2012', 'ESPAÑA', 'JEFE AREA', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000015F', 'LUIS', 'MIGUEL', '07/12/1973', '01/06/2012', 'ESPAÑA', 'MAGO', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000016G', 'MARTA', 'PRECIADO', '19/04/1995', '02/01/2013', 'ESPAÑA', 'RESPONSABLE', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000018H', 'LOREA', 'RIOS', '25/12/2001', '02/01/2014', 'ARGENTINA', 'ACROBATA', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000019J', 'JEAN PAUL', 'BURDEAUX', '16/09/1975', '01/10/2015', 'FRANCIA', 'ACROBATA', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000020A', 'LUIS', 'ALAVA', '02/02/1984', '02/01/2021', 'ESPAÑA', 'JEFE AREA', 0);
INSERT INTO Empleado (idEmpleado, dni, nombre, apellidos, fechaNacimiento, fechaContratacion, nacionalidad, cargo, baja) VALUES (null, '00000021B', 'ALICIA', 'CAMPOREALE', '22/11/1978', '02/01/2021', 'ITALIA', 'ACROBATA', 0);


INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 1001, 'MAGIA KIDS', 50, 'ESPECTACULO DE MAGIA PARA NIÑOS DE 3 A 10 AÑOS', 'SALA 1', 30.5, '15/10/2021', '16:30', 1, 2);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 1002, 'MAGIA KIDS', 50, 'ESPECTACULO DE MAGIA PARA NIÑOS DE 3 A 10 AÑOS', 'SALA 1', 30.5, '16/10/2021', '16:30', 1, 2);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 1003, 'MAGIA KIDS', 50, 'ESPECTACULO DE MAGIA PARA NIÑOS DE 3 A 10 AÑOS', 'SALA 1', 30.5, '17/10/2021', '16:30', 1, 2);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 2101, 'ACROBACIA FUEGO', 150, 'ACROBACIAS EN CINTAS CON PIROTECNIA', 'ANFITEATRO', 20.5, '15/10/2021', '20:45', 1, 8);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 2102, 'ACROBACIA FUEGO', 150, 'ACROBACIAS EN CINTAS CON PIROTECNIA', 'ANFITEATRO', 20.5, '16/10/2021', '20:45', 1, 8);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 2103, 'ACROBACIA FUEGO', 150, 'ACROBACIAS EN CINTAS CON PIROTECNIA', 'ANFITEATRO', 20.5, '17/10/2021', '20:45', 1, 8);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 1004, 'MAGIA KIDS', 50, 'ESPECTACULO DE MAGIA PARA NIÑOS DE 3 A 10 AÑOS', 'SALA 1', 30.5, '22/10/2021', '16:30', 0, 2);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 1005, 'MAGIA KIDS', 50, 'ESPECTACULO DE MAGIA PARA NIÑOS DE 3 A 10 AÑOS', 'SALA 1', 30.5, '23/10/2021', '16:30', 0, 2);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 1006, 'MAGIA KIDS', 50, 'ESPECTACULO DE MAGIA PARA NIÑOS DE 3 A 10 AÑOS', 'SALA 1', 30.5, '24/10/2021', '16:30', 0, 2);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 2104, 'ACROBACIA FUEGO', 150, 'ACROBACIAS EN CINTAS CON PIROTECNIA', 'ANFITEATRO', 20.5, '22/10/2021', '20:45', 0, 8);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 2105, 'ACROBACIA FUEGO', 150, 'ACROBACIAS EN CINTAS CON PIROTECNIA', 'ANFITEATRO', 20.5, '23/10/2021', '20:45', 0, 8);
INSERT INTO Espectaculo (idEspectaculo, numero, nombre, aforo, descripcion, lugar, coste, fecha, horario, baja, idResponsable) VALUES (null, 2106, 'ACROBACIA FUEGO', 150, 'ACROBACIAS EN CINTAS CON PIROTECNIA', 'ANFITEATRO', 20.5, '24/10/2021', '20:45', 0, 8);


INSERT INTO Inscripcion (idInscripcion, idCliente, idEspectaculo, fecha) VALUES (null, 1, 1, '05/10/2021');
INSERT INTO Inscripcion (idInscripcion, idCliente, idEspectaculo, fecha) VALUES (null, 2, 4, '02/10/2021');
INSERT INTO Inscripcion (idInscripcion, idCliente, idEspectaculo, fecha) VALUES (null, 2, 7, '15/10/2021');
INSERT INTO Inscripcion (idInscripcion, idCliente, idEspectaculo, fecha) VALUES (null, 1, 10, '15/10/2021');
